name: "Build"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v17
      with:
        name: vaibhavsagar
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        extraPullNames: ihaskell
    - run: nix-build --keep-going
      env:
        GITHUB_TOKEN: ${{ github.token }}
        TARGET_REPO: ${{ github.repository }}
        RUN_NUMBER: ${{ github.run_number }}
        WORKFLOW: ${{ github.workflow }}
